import { AgentProfile } from '../types.js';

export const agentProfiles: AgentProfile[] = [
  {
    name: 'claude-code',
    displayName: 'Claude Code',
    description: 'Anthropic\'s AI coding agent. Structured conventional commits, high conditional density, co-authored trailers.',
    weights: {
      conventionalCommitRatio: { expected: 0.8, weight: 0.15, tolerance: 0.2 },
      multilineCommitRatio: { expected: 0.4, weight: 0.12, tolerance: 0.3 },
      imperativeMoodRatio: { expected: 0.7, weight: 0.08, tolerance: 0.2 },
      coAuthoredRatio: { expected: 0.7, weight: 0.2, tolerance: 0.3 },
      filesPerCommitAvg: { expected: 5, weight: 0.05, tolerance: 3 },
      singleFileCommitRatio: { expected: 0.3, weight: 0.03, tolerance: 0.2 },
      burstPattern: { expected: 0.3, weight: 0.05, tolerance: 0.2 },
    },
    commitPatterns: [
      /^(feat|fix|refactor|docs|test|chore|style|perf|build|ci)(\(.+\))?!?:/,
      /Co-Authored-By:.*Claude/i,
      /Co-Authored-By:.*anthropic/i,
    ],
    branchPatterns: [
      /^feature\//,
      /^fix\//,
      /^refactor\//,
    ],
    trailerPatterns: [
      /Co-Authored-By:.*Claude/i,
      /Co-Authored-By:.*anthropic/i,
    ],
    keySignals: ['conventional commits', 'co-authored trailers', 'structured messages', 'multi-file changes'],
  },
  {
    name: 'copilot',
    displayName: 'Copilot',
    description: 'GitHub Copilot. Short single-line messages, high single-file ratio, burst commits.',
    weights: {
      conventionalCommitRatio: { expected: 0.2, weight: 0.1, tolerance: 0.15 },
      multilineCommitRatio: { expected: 0.1, weight: 0.15, tolerance: 0.1 },
      singleFileCommitRatio: { expected: 0.7, weight: 0.12, tolerance: 0.2 },
      avgCommitMsgLength: { expected: 30, weight: 0.08, tolerance: 15 },
      burstPattern: { expected: 0.5, weight: 0.1, tolerance: 0.2 },
      filesPerCommitAvg: { expected: 1.5, weight: 0.08, tolerance: 1 },
    },
    commitPatterns: [
      /^Update \w+\.\w+$/,
      /^Create \w+\.\w+$/,
      /^Add \w+/,
      /^Fix \w+/,
    ],
    branchPatterns: [
      /^patch-\d+$/,
      /^copilot\//,
    ],
    trailerPatterns: [
      /Co-authored-by:.*copilot/i,
      /Co-authored-by:.*github/i,
    ],
    keySignals: ['single-line messages', 'single-file commits', 'burst patterns', 'simple verbs'],
  },
  {
    name: 'codex',
    displayName: 'Codex',
    description: 'OpenAI Codex CLI. Multi-line detailed descriptions, moderate file counts, codex branch prefix.',
    weights: {
      multilineCommitRatio: { expected: 0.7, weight: 0.15, tolerance: 0.2 },
      avgCommitMsgLength: { expected: 150, weight: 0.1, tolerance: 50 },
      bulletListRatio: { expected: 0.4, weight: 0.1, tolerance: 0.2 },
      conventionalCommitRatio: { expected: 0.3, weight: 0.05, tolerance: 0.2 },
      filesPerCommitAvg: { expected: 4, weight: 0.05, tolerance: 2 },
    },
    commitPatterns: [
      /^(Add|Implement|Update|Fix|Refactor)\s/,
      /codex/i,
    ],
    branchPatterns: [
      /^codex\//,
      /^codex-/,
    ],
    trailerPatterns: [
      /Generated by Codex/i,
      /codex/i,
    ],
    keySignals: ['multi-line descriptions', 'bullet lists', 'detailed messages', 'codex/* branches'],
  },
  {
    name: 'devin',
    displayName: 'Devin',
    description: 'Cognition\'s Devin. Issue references, plan-execute patterns, devin/* branches.',
    weights: {
      multilineCommitRatio: { expected: 0.6, weight: 0.1, tolerance: 0.2 },
      conventionalCommitRatio: { expected: 0.5, weight: 0.08, tolerance: 0.2 },
      filesPerCommitAvg: { expected: 6, weight: 0.08, tolerance: 3 },
      changeConcentrationGini: { expected: 0.6, weight: 0.08, tolerance: 0.2 },
      bulletListRatio: { expected: 0.3, weight: 0.08, tolerance: 0.2 },
    },
    commitPatterns: [
      /\b(close|closes|fix|fixes|resolve|resolves)\s+#\d+/i,
      /devin/i,
      /plan:/i,
    ],
    branchPatterns: [
      /^devin\//,
      /^devin-/,
    ],
    trailerPatterns: [
      /Devin/i,
      /devin-ai/i,
    ],
    keySignals: ['issue references', 'devin/* branches', 'plan-execute pattern', 'multi-file changes'],
  },
  {
    name: 'cursor',
    displayName: 'Cursor',
    description: 'Cursor IDE agent. Incremental changes, tab-completion artifacts, moderate message length.',
    weights: {
      singleFileCommitRatio: { expected: 0.6, weight: 0.12, tolerance: 0.2 },
      avgCommitMsgLength: { expected: 40, weight: 0.08, tolerance: 20 },
      multilineCommitRatio: { expected: 0.15, weight: 0.1, tolerance: 0.1 },
      filesPerCommitAvg: { expected: 2, weight: 0.08, tolerance: 1.5 },
      burstPattern: { expected: 0.4, weight: 0.08, tolerance: 0.2 },
      conventionalCommitRatio: { expected: 0.3, weight: 0.05, tolerance: 0.2 },
    },
    commitPatterns: [
      /^(Update|Fix|Add|Remove|Refactor)\s/,
      /cursor/i,
    ],
    branchPatterns: [
      /^cursor\//,
    ],
    trailerPatterns: [
      /cursor/i,
    ],
    keySignals: ['incremental changes', 'short messages', 'single-file commits', 'burst patterns'],
  },
  {
    name: 'windsurf',
    displayName: 'Windsurf',
    description: 'Codeium\'s Windsurf agent. Clean structured commits, moderate detail level.',
    weights: {
      conventionalCommitRatio: { expected: 0.5, weight: 0.1, tolerance: 0.2 },
      multilineCommitRatio: { expected: 0.3, weight: 0.08, tolerance: 0.2 },
      filesPerCommitAvg: { expected: 3, weight: 0.05, tolerance: 2 },
      imperativeMoodRatio: { expected: 0.6, weight: 0.08, tolerance: 0.2 },
    },
    commitPatterns: [
      /^(feat|fix|refactor|chore):/,
      /windsurf/i,
      /codeium/i,
    ],
    branchPatterns: [
      /^windsurf\//,
    ],
    trailerPatterns: [
      /windsurf/i,
      /codeium/i,
    ],
    keySignals: ['conventional commits', 'moderate detail', 'clean structure'],
  },
  {
    name: 'aider',
    displayName: 'Aider',
    description: 'Aider CLI tool. Distinctive aider: prefix, --message artifacts, co-authored trailers.',
    weights: {
      coAuthoredRatio: { expected: 0.8, weight: 0.15, tolerance: 0.2 },
      conventionalCommitRatio: { expected: 0.3, weight: 0.05, tolerance: 0.2 },
      multilineCommitRatio: { expected: 0.3, weight: 0.08, tolerance: 0.2 },
      singleFileCommitRatio: { expected: 0.5, weight: 0.05, tolerance: 0.2 },
    },
    commitPatterns: [
      /^aider:/i,
      /aider/i,
      /--message/,
    ],
    branchPatterns: [
      /^aider\//,
    ],
    trailerPatterns: [
      /Co-authored-by:.*aider/i,
      /aider/i,
    ],
    keySignals: ['aider: prefix', 'co-authored trailers', '--message artifacts'],
  },
];
